version: 2

updates:
  - package-ecosystem: 'npm'
    directory: /
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /docs/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /tests-e2e/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/a5es5/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/a5es2015/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/a6/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/a7/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/a8/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/a9/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/a10/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/a11/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/a12/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/a13/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/a14/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/a15/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/a16/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/jasmine/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/jest/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/min/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: /e2e/nx/
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'docker'
    directory: /
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'
