os: linux
language: node_js
node_js:
  - 10
dist: trusty
addons:
  chrome: stable
git:
  autocrlf: false
install:
  - npm install
script:
  - npm run test:angular-versions
cache:
  npm: false
  directories:
    - $HOME/.npm
    - $HOME/.node-gyp
    - node_modules
    - e2e/angular5/node_modules
    - e2e/angular6/node_modules
    - e2e/angular7/node_modules
    - e2e/angular8/node_modules
    - e2e/angular9-ivy-false/node_modules
    - e2e/angular9-ivy-true/node_modules
