language: node_js

node_js: 6

before_install:
  - npm install -g npm@4
  - npm --version

install:
  - ./ci/install.sh

script:
  - npm run lint
  - npm run build:ci
  - npm run test:unit
  - npm test
