language: node_js
node_js:
  - "v6.11.1"
  - "v7.10.1"
  - "v8.0.0"
sudo: required
dist: trusty
addons:
    chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
before_install:
  - npm cache clean --force
script: npm run lint && npm test
matrix:
  notifications:
    email:
      recipients:
        - ike18t@gmail.com
      on_success: change
      on_failure: change
