sudo: required

language: node_js

node_js: 8

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

addons:
  chrome: stable

install:
  - npm run bootstrap

script:
  - npm run ci
