environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - ci\install.bat

test_script:
  - node --version
  - npm --version
  - npm run lint
  - ci\run.bat

build: off