environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\npm;%PATH%
  - node -v
  - npm -v
  - npm run bootstrap

test_script:
  - npm run ci

build: off
