version: '3'

services:
  ng-mocks:
    image: satantime/puppeteer-node:18.13.0
    working_dir: /app
    volumes:
      - .:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit

  docs:
    image: satantime/puppeteer-node:18.13.0
    working_dir: /app
    volumes:
      - ./docs:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit

  e2e:
    image: satantime/puppeteer-node:18.13.0
    working_dir: /app
    volumes:
      - ./tests-e2e:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit

  a5es5:
    image: satantime/puppeteer-node:8.17.0
    working_dir: /app
    volumes:
      - ./e2e/a5es5:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit
      - --no-optional

  a5es2015:
    image: satantime/puppeteer-node:8.17.0
    working_dir: /app
    volumes:
      - ./e2e/a5es2015:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit
      - --no-optional

  a6:
    image: satantime/puppeteer-node:8.17.0
    working_dir: /app
    volumes:
      - ./e2e/a6:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit
      - --no-optional

  a7:
    image: satantime/puppeteer-node:8.17.0
    working_dir: /app
    volumes:
      - ./e2e/a7:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit
      - --no-optional

  a8:
    image: satantime/puppeteer-node:10.24.1
    working_dir: /app
    volumes:
      - ./e2e/a8:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit
      - --no-optional

  a9:
    image: satantime/puppeteer-node:12.22.12
    working_dir: /app
    volumes:
      - ./e2e/a9:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit
      - --no-optional

  a10:
    image: satantime/puppeteer-node:12.22.12
    working_dir: /app
    volumes:
      - ./e2e/a10:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit
      - --no-optional

  a11:
    image: satantime/puppeteer-node:12.22.12
    working_dir: /app
    volumes:
      - ./e2e/a11:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit
      - --no-optional

  a12:
    image: satantime/puppeteer-node:12.22.12
    working_dir: /app
    volumes:
      - ./e2e/a12:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit
      - --no-optional

  a13:
    image: satantime/puppeteer-node:12.22.12
    working_dir: /app
    volumes:
      - ./e2e/a13:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit
      - --no-optional

  a14:
    image: satantime/puppeteer-node:16.19.0
    working_dir: /app
    volumes:
      - ./e2e/a14:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit

  a15:
    image: satantime/puppeteer-node:16.19.0
    working_dir: /app
    volumes:
      - ./e2e/a15:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit

  jasmine:
    image: satantime/puppeteer-node:18.13.0
    working_dir: /app
    volumes:
      - ./e2e/jasmine:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit

  jest:
    image: satantime/puppeteer-node:18.13.0
    working_dir: /app
    volumes:
      - ./e2e/jest:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit

  min:
    image: satantime/puppeteer-node:18.13.0
    working_dir: /app
    volumes:
      - ./e2e/min:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit

  nx:
    image: satantime/puppeteer-node:18.13.0
    working_dir: /app
    volumes:
      - ./e2e/nx:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit

volumes:
  npm:
  gyp:
